### DISCUSSION TITLE
有个问题，（是一个不会java的前端实习生—）求帮助！！！

### DISCUSSION THREAD

**Discussion by nozuo-ux** [halo-dev/halo#2786] [Q&A] [answered]
就是跟着2.0的文档步骤做（开发运行环境的那一项）做到运行halo项目那里，等halo的相关依赖安装好后，点击运行，运行一下就停止了 结果显示 “进程结束，退出代码0”这是怎么回事
下面是截图：
![image](https://user-images.githubusercontent.com/79638331/204118049-025cb6cd-2969-4ee6-860a-cf0a63bbd5f5.png)
![image](https://user-images.githubusercontent.com/79638331/204118059-4209d4d1-8914-4c92-a210-2e60f8a8873a.png)
![image](https://user-images.githubusercontent.com/79638331/204118073-74d01a72-cc78-4224-aa6e-f037578701ac.png)

**Comment by ruibaby** [comment]
应该是因为不兼容 Windows 平台的路径规则导致的。你可以参考 https://github.com/halo-dev/halo/pull/2753 中的方案修改一下配置文件。

**Comment by nozuo-ux** [comment]
还有就是，文档中这图片中是指的是把这个 “src/main/resources/application-dev.yaml”路径下的 “application-dev.yaml”修改为”application-local.yaml“这个文件名对吧，并把图片中的代码（蓝色圈部分）
![image](https://user-images.githubusercontent.com/79638331/204121160-5567c1a4-20d0-41ad-9d1c-a8a3451e5102.png)

全部改为下面图片的代码
![image](https://user-images.githubusercontent.com/79638331/204121122-6399edcc-0467-40af-b3d2-ce6738ba6bdd.png)

谢谢你的解答

**Comment by ruibaby** [comment]
@nozuo-ux 可以直接使用 https://github.com/halo-dev/halo/pull/2753#pullrequestreview-1192918486

console 的配置往后面追加就行了。

**Comment by nozuo-ux** [comment, marked as answer]
我按照这个网址的  [网址](https://github.com/halo-dev/halo/pull/2753/files#diff-1c1a48558b5d0aec91b5c1aad9784437fcdd756764ee54697b1750cd2dfb46c5) 内容修改了，点击运行还是不行啊，还是和开始一样点了运行就一会就停止运行了 #

**Reply by guqing** [reply]
尝试在 `src/main/resources/` 下创建 `application-win.yaml`写入如下内容：
```yaml
spring:
  r2dbc:
    url: r2dbc:h2:file:///~/halo2-dev/db/halo-next?MODE=MySQL&DB_CLOSE_ON_EXIT=FALSE
halo:
  work-dir: ${user.home}/halo2-dev
  security:
    initializer:
      super-admin-username: admin
      super-admin-password: admin
```
然后启动时将之前的 local profile 改为 win
<img width="726" alt="image" src="https://user-images.githubusercontent.com/38999863/204208088-d61bea45-f9b9-409e-b1e8-d0cdba3b6040.png">
