### DISCUSSION TITLE
大佬们帮忙看看，迁移Halo后数据丢失

### DISCUSSION THREAD

**Discussion by kekylin** [halo-dev/halo#6013] [General]
事发经过：前两天硬盘损坏，然后就使用rsync命令复制整个docker的持久化配置文件到另外一块磁盘，当时心急，忘记使用博客自带的备份工具打包备份，而是直接复制了整个容器的持久化配置，因为之前重装系统，重新拉取镜像回来运行就可以了，结果这次迁移之后起容器，却显示是新安装的，无法读取到旧的数据，即使是把备份的docker配置重新放回原来的路径也是不行。
**求助解决方法：请问还有办法能读取到已有的数据吗？写了很多文章，不想弄丢了。**
系统是Debian 12.5，使用的是Docker部署Halo，官方的文档示例，只是修改了账户密码和配置路径，具体配置如下所示，账户密码这里简化为test展示。
```yaml
version: "3"

services:
  halo:
    image: halohub/halo:2.14.0
    container_name: halo
    restart: always
    depends_on:
      halodb:
        condition: service_healthy
    networks:
      halo_network:
    volumes:
      - /srv/volume_1/data/docker/halo/blog:/root/.halo2
    ports:
      - "8090:8090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health/readiness"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s          
    command:
      - --spring.r2dbc.url=r2dbc:pool:postgresql://halodb/halo
      - --spring.r2dbc.username=halo
      # PostgreSQL 的密码，请保证与下方 POSTGRES_PASSWORD 的变量值一致。
      - --spring.r2dbc.password=test
      - --spring.sql.init.platform=postgresql
      # 外部访问地址，请根据实际需要修改
      - --halo.external-url=https://localhost:8090/
      # 初始化的超级管理员用户名
      - --halo.security.initializer.superadminusername=test
      # 初始化的超级管理员密码
      - --halo.security.initializer.superadminpassword=test
  halodb:
    image: postgres:15.4
    container_name: halodb
    restart: always
    networks:
      halo_network:
    volumes:
      - /srv/volume_1/data/docker/halo/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=halo
      - POSTGRES_DB=halo
      - PGUSER=halo

networks:
  halo_network:
```
  备份的文件都显示还在：
![image](https://github.com/halo-dev/halo/assets/65521882/3962a668-c5bd-4245-8d4e-d11343be9905)
![image](https://github.com/halo-dev/halo/assets/65521882/d154af0f-54ce-47fc-9aea-525583ded2cc)
