### DISCUSSION TITLE
无法切换为mysql数据源

### DISCUSSION THREAD

**Discussion by LockonS** [halo-dev/halo#6521] [Q&A]
### System information

Version: 2.18
Database: MySQL/8.0.36

### What is the project operation method?

Fat Jar

### What happened?

使用systemd启动服务，在/home/halo/.halo2/application.yml 中数据库部分配置如下
启动服务后halo只会创建h2数据库，但是不会连接到mysql

```
spring:
  # 数据库配置，支持 MySQL、MariaDB、PostgreSQL、H2 Database，具体配置方式可以参考下面的数据库配置
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/halo?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: halo
    password: HaloService-2024
  sql:
    init:
      mode: always
      # 需要配合 r2dbc 的配置进行改动
      platform: mysql
```
