### DISCUSSION TITLE
基于plugin-oauth2插件做二开，插件里定义的POST请求需要授权，而GET请求不需要

### DISCUSSION THREAD

**Discussion by langaobai** [halo-dev/halo#6723] [Q&A] [answered]
如标题所述，我需要post请求也能够匿名访问，而不是401 (Unauthorized)，但不论如何调整都不行，GET请求就不会被拦截；

已经想尽办法，只差源码调试了

**Comment by guqing** [comment]
参考文档 [聚合角色](https://docs.halo.run/developer-guide/plugin/api-reference/server/role-template#:~:text=%E5%A6%82%E6%9E%9C%E4%BD%A0%E6%83%B3%E5%B0%86%E4%BD%A0%E5%86%99%E7%9A%84%E8%B5%84%E6%BA%90%E5%9E%8B%20APIs%20%E5%85%AC%E5%BC%80%E7%BB%99%E6%89%80%E6%9C%89%E7%94%A8%E6%88%B7%E8%AE%BF%E9%97%AE%EF%BC%8C%E8%BF%99%E6%97%B6%E4%BD%A0%E5%8F%AF%E4%BB%A5%E9%80%9A%E8%BF%87%E8%81%9A%E5%90%88%E8%A7%92%E8%89%B2%E6%9D%A5%E5%B0%86%E4%BD%A0%E7%9A%84%E8%B5%84%E6%BA%90%E5%9E%8B%20APIs%20%E7%9A%84%E8%A7%92%E8%89%B2%E8%81%9A%E5%90%88%E5%88%B0%20anonymous%20%E8%A7%92%E8%89%B2%E4%B8%AD%EF%BC%8C%E8%BF%99%E6%A0%B7%E6%89%80%E6%9C%89%E7%94%A8%E6%88%B7%E9%83%BD%E5%8F%AF%E4%BB%A5%E8%AE%BF%E9%97%AE%E4%BD%A0%E7%9A%84%E8%B5%84%E6%BA%90%E5%9E%8B%20APIs%20%E4%BA%86%E3%80%82) 的说明，你需要声明一个 role template 的 yaml 并加上 `rbac.authorization.halo.run/aggregate-to-anonymous: "true"` label 即可

**Reply by langaobai** [reply]
后面参考了，完整的如下：
```yml
apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-stormlink-accessible
  labels:
    halo.run/role-template: "true"
    halo.run/hidden: "true"
    rbac.authorization.halo.run/aggregate-to-anonymous: "true"
  annotations:
    rbac.authorization.halo.run/module: "xxxx"
    rbac.authorization.halo.run/display-name: "匿名访问"
rules:
    verbs: [ "get", "list" ]
  - apiGroups: ["medsta.halo.run"]
    resources: ["plugins"]
    resourceNames: ["loginQrCode"]
    verbs: [ "get", "list" ]
  - apiGroups: ["medsta.halo.run"]
    resources: ["plugins"]
    resourceNames: ["userLogin"]
    verbs: [ "get", "list" ]
  - apiGroups: ["medsta.halo.run"]
    resources: ["plugins"]
    resourceNames: ["wechatCheck"]
    verbs: [ "get","create","list" ]
```
这里最后有两个方法，get和post都是同名请求，但是get可以post就不行了

**Reply by guqing** [reply]
@langaobai 

> 后面参考了，完整的如下：
> 
> ```yml
> 
>     resources: ["plugins"]
> 
>     resourceNames: ["wechatCheck"]
> 
>     verbs: [ "get","create","list" ]
> 
> ```
> 
> 这里最后有两个方法，get和post都是同名请求，但是get可以post就不行了
> 
> 

因为 create 的 verb 不可以有 resource Name 创建时传递路径参数的名称被认为是非资源型

你可以使用 https://docs.halo.run/developer-guide/plugin/basics/devtools#generateroletemplates-%E4%BB%BB%E5%8A%A1 这个最近新提供的 gradle task 来生成基础角色模板然后在自己组合一下避免出错

**Reply by guqing** [reply]
快速的解决方案就是将你 post 的路由加一个 subresource 作为 action
如 /plugins/wechatCheck/check
然后不要与 list 和 get 配置在一起 分开

resources: ["plugins/check"]
resourceNames: ["wechatCheck"]
verbs: [ "create" ]

**Reply by langaobai** [reply]
好的，我都试试看，你上面推荐的使用gradlew方法失败，找不到这个task；

![image](https://github.com/user-attachments/assets/3673e47b-6ba1-4a73-87cc-461e350662d3)

**Reply by langaobai** [reply]
已经按照你说的进行快速配置，但还是不行

![image](https://github.com/user-attachments/assets/7d4226ef-589f-47f8-81b1-aba4b36b53ef)

![image](https://github.com/user-attachments/assets/c8ba4f6a-4ad8-4efc-9116-006f8fc2b4be)

**Reply by guqing** [reply]
> 好的，我都试试看，你上面推荐的使用gradlew方法失败，找不到这个task；

Hi @langaobai 

先通过
```shell
./gradlew -version
```
查看 gradle 版本是否为 8.3 以上，如果不是先升级 gradle 版本
```shell
./gradlew wrapper --gradle-version=8.9
```
然后将build.gradle 中的 devtools gradle 插件升级到 0.3.0
```
plugins {
  id "run.halo.plugin.devtools" version "0.3.0"
}
```
然后需要将你所有的路由的加上 Springdoc 的注解或者通过 SpringdocRouteBuilder 来构建这样才能被 OpenAPI 识别到才能构建出角色模板，这一步虽然麻烦但是可以即决配置 roleTemplates 和调用 API 繁琐的问题，因为可以生成 API Client

**Reply by guqing** [reply]
看起来你 https://github.com/orgs/halo-dev/discussions/6723#discussioncomment-11117556 提到的路由已经通过 SpringdocRouteBuilder 定义并能在 swagger-ui 上看到，那么就只需要配置好 gradle task 即可

**Reply by guqing** [reply]
@langaobai 对于 `http://localhost:8090/apis/medsta.halo.run/v1alpha1/plugins/wechat/checkMsg`
这个 API 正确的配置如下：
```yaml
rules:
  - apiGroups: ["medsta.halo.run"]
    resources: ["plugins/checkMsg"]
    resourceNames: ["wechat"]
    verbs: ["create"]
```
参考规则：`/apis/<group>/<version>/<extension>/{extensionname}/<subextension>`
参考文档：https://docs.halo.run/developer-guide/plugin/api-reference/server/extension#extension-apis

**Reply by langaobai** [reply]
通过更新devtools gradle版本之后，已可以找到[generateRoleTemplates],但目前生成的roleTemplates.yaml是空的，怀疑是因为openapi的json文件生成api为空；

这里之前我生成过openapi的json文件.里面是有api的，并通过api生成了前端请求API client，但是后续加入了一些新方法后，生成的就是空;

```yml
haloPlugin {
    openApi {
        outputDir = file("$rootDir/api-docs/openapi/v3_0")
        groupingRules {
            medstasV1alpha1Api {
                displayName = 'Extension API for plugin-medsta'
                pathsToMatch = [
                        '/apis/medsta.halo.run/v1alpha1/authorizedclients/**',
                        '/apis/medsta.halo.run/v1alpha1/oauth2clientregistrations/**',
                        '/apis/medsta.halo.run/v1alpha1/stormsmartstatisticslinks/**',
                        '/apis/medsta.halo.run/v1alpha1/stormsmartstatisticslinkgroups/**',
                        '/apis/medsta.halo.run/v1alpha1/plugins/**'
                ]
            }
        }
        groupedApiMappings = [
                '/v3/api-docs/medstasV1alpha1Api': 'medstasV1alpha1Api.json'
        ]
        generator {
            outputDir = file("${projectDir}/ui/src/api/generated")
        }
    }
}

```

上面是我的配置，生成如下：

![image](https://github.com/user-attachments/assets/1631e358-5b2a-441c-91c8-e6d74cfe1982)

虽然插件里是空的，但是halo根地址下的swagger-ui,是可以找到对应的api
![image](https://github.com/user-attachments/assets/113b91fb-2c65-4d5a-ae28-91e02cef02e2)

**Reply by guqing** [reply]
> 通过更新devtools gradle版本之后，已可以找到[generateRoleTemplates],但目前生成的roleTemplates.yaml是空的，怀疑是因为openapi的json文件生成api为空；
> 
> 这里之前我生成过openapi的json文件.里面是有api的，并通过api生成了前端请求API client，但是后续加入了一些新方法后，生成的就是空;
> 
> ```yaml
> haloPlugin {
>     openApi {
>         outputDir = file("$rootDir/api-docs/openapi/v3_0")
>         groupingRules {
>         groupedApiMappings = [
>                 '/v3/api-docs/medstasV1alpha1Api': 'medstasV1alpha1Api.json'
>         ]

@langaobai  将 groupedApiMappings 中的 `/v3/api-docs/medstasV1alpha1Api` 替换为下图框起来中区域的地址但是不要照着下面的写，因为你写的 tag 不一样它也不一样，在下图选择
<img width="657" alt="image" src="https://github.com/user-attachments/assets/32e2ee3f-ca80-494e-830d-ed390b98b900">

，需要是包含了你需要的 API 的 group

<img width="748" alt="image" src="https://github.com/user-attachments/assets/d4deb19c-112c-422f-b592-be618714bb98">

或者直接写为`/v3/api-docs/apis_aggregated.api_v1alpha1`

**Reply by guqing** [reply]
实在不行就提交代码，让我来

**Reply by langaobai** [reply]
这个写法我是参考了plugin-link插件的方式，几乎是相同的；
如果我将        
```yml
groupedApiMappings = [
                '/v3/api-docs/medstasV1alpha1Api': 'medstasV1alpha1Api.json'
        ]
```
修改为
```yml
groupedApiMappings = [
                '/v3/api-docs/apis_aggregated.api_v1alpha1': 'aggregated.json'
        ]
```

这样会将apis_aggregated.api_v1alpha1全部导出到插件位置，而不是我选定的那几个

**Reply by langaobai** [reply]
我使用全部生成的openapi来生成角色模板，然后复制改造自己的角色模板发现还是不行
生成的
![image](https://github.com/user-attachments/assets/f765091c-f2c5-49da-bb85-fb03b327bc35)

改造自己的
![image](https://github.com/user-attachments/assets/00d92d4f-ed1d-462c-a7e7-5618c173b704)

**Reply by guqing** [reply]
> 我使用全部生成的openapi来生成角色模板，然后复制改造自己的角色模板发现还是不行 生成的 ![image](https://private-user-

@langaobai  请看 VCR，我随便在 links 插件中加了一个跟你一样的路由

```java
 @Bean
RouterFunction<ServerResponse> linkRouterFunction() {
    return RouterFunctions.route()
        .POST("/apis/medsta.halo.run/v1alpha1/plugins/wechat/checkMsg", this::checkMsg)
        .build();
}

private Mono<ServerResponse> checkMsg(ServerRequest request) {
    return ServerResponse.ok().bodyValue("Hello checkMsg");
}
```
并提供以下角色模板
```yaml
apiVersion: v1alpha1
kind: Role
metadata:
  name: medsta-wechat
  labels:
    halo.run/role-template: "true"
    # 由于需要将这一组 API 公开访问（必须认证和授权）因此在 添加这一 labels 聚合到 anonymous 角色
    rbac.authorization.halo.run/aggregate-to-anonymous: "true"
rules:
  - apiGroups: [ "medsta.halo.run" ]
    resources: [ "plugins/checkMsg" ]
    resourceNames: [ "wechat" ]
    verbs: [ "create" ]
```
参考 [角色聚合文档](https://docs.halo.run/developer-guide/plugin/security/rbac/#%E8%81%9A%E5%90%88%E8%A7%92%E8%89%B2)

https://github.com/user-attachments/assets/6714fb20-3d83-4e17-87c5-c6101ca0d8da
