### DISCUSSION TITLE
Proposal：为应用市场插件添加依赖/推荐应用支持

### DISCUSSION THREAD

**Discussion by ruibaby** [halo-dev/halo#7105] [Ideas]
## 摘要

目前 Halo 的单个主题或者插件（尤其是主题）可能会依赖于其他插件，虽然目前插件已经在底层支持了插件依赖，但没有很好的办法引导用户安装，尤其是依赖的还只是 `metadata.name`，用户即便看到依赖提示，可能仍然无法知道具体需要安装什么插件。

所以我建议专门为应用市场插件提供元数据定义，专门用于定义依赖/或者推荐应用，可以实现用户在应用市场安装主题或者插件之后，如果有依赖/推荐定义，在安装完之后可以显示引导安装其他推荐或者依赖插件的界面，引导用户安装。

## 定义方式

以默认主题为例。

```yaml
apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-earth
  annotations:
    "store.halo.run/app-id": "app-KgWqR"
     # 推荐安装 app-SnwWD（瞬间），app-sqpgf（highlight.js 代码高亮）
    "store.halo.run/recommend-apps": ["app-SnwWD", "app-sqpgf"]
     # 依赖 app-UpUJA（编辑器超链接卡片）
    "store.halo.run/required-apps": ["app-UpUJA"]
spec:
  displayName: Earth
  author:
    name: Halo
    website: https://www.halo.run
  description: Default theme for Halo 2.0
  logo: https://www.halo.run/logo
  homepage: https://www.halo.run/store/apps/app-KgWqR
  repo: https://github.com/halo-dev/theme-earth
  issues: https://github.com/halo-dev/theme-earth/issues
  settingName: "theme-earth-setting"
  configMapName: "theme-earth-configMap"
  version: 1.12.1
  requires: ">=2.20.0"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/halo-dev/theme-earth/blob/main/LICENSE"
```

说明：

1. `store.halo.run/recommend-apps`：推荐应用的定义，为应用市场应用 id 的数组。
2. `store.halo.run/required-apps`：依赖应用的定义，为应用市场应用 id 的数组。

最终用户在应用市场安装这个主题之后，会解析这个定义，然后判断是否已经安装，如果有未安装的应用，会根据应用 id 显示出所需的应用，引导用户安装。

## 疑问

Q1. 为什么不直接在插件/主题定义的 spec 中定义依赖？

因为 Halo 并不依赖应用市场插件，应用市场插件应该始终为可选，用户可以自行决定是否要使用应用市场插件，所以我认为放在 spec 中并不合适，这需要修改 Halo 本身的代码。

Q2. 为什么插件有了 `spec.pluginDependencies` 字段，还需要单独定义这两个元数据？

这只是底层插件机制的依赖，如果按照这个字段去实现，以目前应用市场的系统设计无法完成，并且可能仍然需要为应用市场插件去修改 Halo 的代码，这可能会导致强依赖。我认为 `store.halo.run/recommend-apps` 和 `store.halo.run/required-apps` 并不需要和 `spec.pluginDependencies` 有关联，这应该让开发者自行决定。

## 相关讨论

1. https://github.com/orgs/halo-dev/discussions/7007
2. https://github.com/halo-dev/halo/issues/2296

## 参考：

1. VSCode 插件依赖定义：https://code.visualstudio.com/api/references/extension-manifest#:~:text=vscode.csharp.-,extensionDependencies,-array
3. VSCode 项目插件推荐定义：https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions
