### DISCUSSION TITLE
自定义元数据表单增加字段后在主题中使用时找不到字段

### DISCUSSION THREAD

**Discussion by exialin** [halo-dev/halo#7163] [Q&A]
我在尝试基于[theme-ocean](https://github.com/f2ccloud/theme-ocean)开发主题的过程中，参考[元数据表单定义](https://docs.halo.run/developer-guide/annotations-form)给Post增加了一个字段，用于控制是否展示侧边栏：
```yaml
apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  name: annotation-post
spec:
  targetRef:
    group: content.halo.run
    kind: Post
  formSchema:
    - $formkit: "radio"
      name: "show_sidebar"
      label: "是否显示侧边栏"
      value: "true"
      options:
        - label: "是"
          value: "true"
        - label: "否"
          value: "false"
```

接着修改`https://github.com/f2ccloud/theme-ocean/blob/master/templates/post.html`第5行最后的`isSidebar`变量：
```html
th:replace="~{modules/layout :: html(title = ${post.spec.title} + ' - ' + ${site.title}, header = ~{::header}, content = ~{::content}, head = null, footer = ~{::footer}, sidebar = ~{::sidebar}, contentClass = ${theme.config.layout.content_header} and ${not #strings.isEmpty(post.spec.cover)} ? '!-mt-20' : '', isSidebar = ${post.metadata.annotations.show_sidebar == 'true'})}"
```

但这里有一个问题，对于存量的文章，由于没有这个属性，访问的时候会报错，后台日志：
```
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1008E: Property or field 'show_sidebar' cannot be found on object of type 'java.util.LinkedHashMap' - maybe not public or not valid?
```

一种方法是修改所有文章的设置，将“是否显示侧边栏”改为“否”，但更好的方法是判断`show_sidebar`属性是否存在。由于我对Thymeleaf不熟，想问下有没有什么比较好的方法？

另外，新创建的文章有一个问题，必须点击“设置”并保存一次，文章才会有`show_sidebar`属性，否则访问报错，请问这个又应该如何解决？
<img width="1173" alt="image" src="https://github.com/user-attachments/assets/76516ba1-aa65-4fed-9563-992608c73936" />
