### ISSUE TITLE
docker-compose启动的jvm配置不生效

### ISSUE THREAD

**Issue by QianXun0827** [halo-dev/halo#1028]
## 我的环境

版本：1.3.2
数据库：H2 1.4.196 (2017-06-10)
运行模式：production
User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
---

## 错误日志

无
---

## 期望行为

jvm配置生效
## 当前行为
```yml
halo:
  restart: always
  image: ruibaby/halo
  container_name: halo
  ports:
    - 8090:8090
  environment:
    - JVM_XMS=300m
    - JVM_XMX=300m
  volumes:
    - ./data:/root/.halo
    - ./backup:/tmp/halo-backup
```

![image](https://user-images.githubusercontent.com/40862062/89874700-cc080b00-dbee-11ea-95dc-80645148078d.png)
启动后的内存截图
