### ISSUE TITLE
URL of h2 console

### ISSUE THREAD

**Issue by salahatwa** [halo-dev/halo#1231]
Can  you please share url of h2 console , i treid to open  following url
http://127.0.0.1:8090/h2-console
but it give me 404 not-found

**Comment by JohnNiang** [comment]
First of all, you have to make some changes in ~/.halo/application.yaml.

```yaml
spring:
  datasource:

    # H2 database configuration.
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.halo/db/halo
    username: admin
    password: 123456

  # H2 database console configuration.
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true
```
