### ISSUE TITLE
application-dev.yaml 中 h2-console 的默认状态修改为关闭。

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#1745]
### Your current Halo version

1.5.0-alpha.2

### Describe this feature

防止有使用者勿使用 dev 配置文件，从而带来隐性的风险。

**Comment by JohnNiang** [comment]
我不认为我们应该去将 dev 配置文件中的 `h2.console.enabled` 更改为 false。如果以上逻辑成立，我们是不是也得担心用户误操作，把 `h2.console.enabled` 更改为 true 呢：

```yaml
  h2:
    console:
      enabled: true
```

风险并不在这个配置，而是在用户是否谨慎使用配置。
