### ISSUE TITLE
完善用户认证和授权机制

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#2141]
### 你当前使用的版本

2.0.0-SNAPSHOT

### 描述一下此特性

在完善用户认证和授权机制之前，需要先完成以下两个模块：

#### 用户模型

```yaml
apiVersion: v1alpha1
kind: User
metadata:
    name: haloer
spec:
    displayName: Awersome Haloer
    avatar: https://halo.run/logo
    email: haloer@halo.run
    phone: # optional
    password: "$2a$12$R9h/cIPz0gi.URNNX3kh2OPST9/PgBkqquzi.Ss7KIUgO2t0jWMUW"
    bio: I'm from Halo organization.
    registeredAt: "2022-06-07 11:34:39"
    twoFactorAuthEnabled: false
    disabled: false
    loginHistoryLimit: 10 # Default is 10 records
status:
    lastLoginAt: "2022-06-07 12:30:30"
    loginHistory:
        -   loginAt: "2022-06-07 12:30:30"
            sourceIp: "192.168.0.2"
            userAgent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
            type: Success
        -   loginAt: "2022-06-07 11:30:30"
            sourceIp: "192.168.0.3"
            userAgent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
            type: Failure
            message: "Invalid credentials"
```

#### 实现 ReactiveUserDetailService

由于没有用户体系，目前仅仅创建了一个用于测试的 MapReactiveUserDetailsService。

```java
public class WebServerSecurityConfig {

    @Bean
    ReactiveUserDetailsService userDetailsService() {
        //TODO Implement details service when User Extension is ready.
        return new MapReactiveUserDetailsService(
                // for test
                User.withDefaultPasswordEncoder().username("user").password("password").roles("USER")
                        .build(),
                // for test
                User.withDefaultPasswordEncoder().username("admin").password("password").roles("ADMIN")
                        .build());
    }
}
```

### 附加信息

/kind feature
/area core
/milestone 2.0
/assign
