### ISSUE TITLE
允许自动生成自定义模型数据的名称

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#2309]
### 你当前使用的版本

2.0.0-SNAPSHOT

### 描述一下此特性

我们期望为自定义模型的 metadata 新增 generateName 字段。如果该字段设置，将会自动生成以 generateName 为前缀的随机名称。

自定义模型数据配置样例如下：

```yaml
apiVersion: v1alpha1
metadata:
    generateName: halo-
```

最终生成的数据如下：

```yaml
apiVersion: v1alpha1
metadata:
    generateName: halo-
    name: halo-xyz
```

### 附加信息

/area core
/milestone 2.0
/kind feature
/assign
