### ISSUE TITLE
关于主题配置项默认值问题

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#2414]
### Your current Halo version

2.0.0

### Describe this feature

目前主题安装后基本都有 settings.yaml 并且其中配置了设置的默认值
```yaml
apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-anatole-setting
spec:
  - group: basic
    label: 基本设置
    formSchema:
      - $formkit: select
        name: sidebar_width
        label: 侧边栏宽度
        options:
          "20%": 20%
          "30%": 30%
          "40%": 40%
          "50%": 50%
        value: "40%"
```
如上所示，group=basic的 item 的 formSchema 是表单 schema，如果有默认值会在其中又一个 `value` 属性，例如 `40%`
但是主题首次安装需要在主题设置点击保存才能将默认值同步到 ConfigMap 中。
这显得很繁琐，而且不开箱即用，需要对此进行优化：
实现方式：
1. 主题安装时，console 端模拟保存动作，虽然能行但不建议
2. 安装主题时，后端处理默认值，读取 settings.yaml，`formSchema[index].value` 即为默认值根据
> [group].formSchema[idnex].name=formSchema[index].value的方式即可创建 configMap，其中 [group] 表示组名占位符，[index]表示数组索引占位符

@halo-dev/sig-halo 你们怎么看

### Additional information

/kind improvement
/area core
/milestone 2.0
