### ISSUE TITLE
为2.0增加Docker以application.yaml配置的方式启动

### ISSUE THREAD

**Issue by suk1da** [halo-dev/halo#2812]
### 你当前使用的版本

1.6.0

### 描述一下此特性

因为1.x的版本启动都是按照application.yaml的配置方式启动的，希望2.0也能通过此种方式启动。

**Comment by wan92hen** [comment]
根据 [Spring Boot 的文档](https://docs.spring.io/spring-boot/docs/1.0.1.RELEASE/reference/html/boot-features-external-config.html#boot-features-external-config-yaml)，把配置文件挂载到 Halo 容器的 `/application/config/application.yaml` 目录就可以加载这个配置文件。

参考 Compose 修改：
```
  halo_next:
    image: halohub/halo-dev:2.0.0
    container_name: halo_next
    restart: on-failure:3
    depends_on:
      halo_db:
        condition: service_healthy
    networks:
      halo_network:
    volumes:
      - ./:/root/.halo2
      # 挂载配置文件到指定目录
      - ./application.yaml:/application/config/application.yaml
    ports:
      - "8090:8090"
```
