### ISSUE TITLE
为什么登不上

### ISSUE THREAD

**Issue by Cystee** [halo-dev/halo#2824]
### 是什么版本出现了此问题？

2.0.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://me.casecori.top/console/#/login

### 发生了什么？

初次安装，我正确配置了 `HALO_SECURITY_INITIALIZER_SUPERADMINPASSWORD=passwd`，然而输入用户 admin，密码 passwd，提示用户名或密码错误。然后我去 `/var/lib/docker/containers/cda44be3e90ce49dbc45de842ae5974a72e1ca842599b96a6afa7123c9a652f4` 改了 `config.v2.json` 里的 `user:"passwd"`，最后仍然报错。

### 相关日志输出

```shell
太长了，我放在附加信息里了，第一条。
```

### 附加信息

http://101.32.39.68/gh/cda44be3e90ce49dbc45de842ae5974a72e1ca842599b96a6afa7123c9a652f4-json.log
http://101.32.39.68/gh/config.v2.json

**Comment by JohnNiang** [comment]
建议清除掉 `~/.halo2` 重试。

/kind support

**Comment by Cystee** [comment]
成功了，十分感谢！但我现在还有个问题，点击文章为什么跳转到 localhost，怎么让他跳转到域名？

**Comment by Cystee** [comment]
尝试解决，换成 Docker Compose 部署，但是没有成功，以下是 `docker-compose.yaml`：

```yaml
version: "3"

services:
  halo:
    image: halohub/halo:2.0.0
    container_name: halo
    restart: on-failure:3
    depends_on:
      halodb:
        condition: service_healthy
    networks:
      halo_network:
    volumes:
      - ./:/root/.halo2
    ports:
      - "8090:8090"
    environment:
      - SPRING_R2DBC_URL=r2dbc:pool:mysql://halodb:3333/halo
      - SPRING_R2DBC_USERNAME=me
      # MySQL 的密码，请保证与下方 MYSQL_ROOT_PASSWORD 的变量值一致。
      - SPRING_R2DBC_PASSWORD=Coreeseeds14@@
      - SPRING_SQL_INIT_PLATFORM=mysql
      # 外部访问地址，请根据实际需要修改
      - HALO_EXTERNAL_URL=https://me.casecori.top/
      # 初始化的超级管理员用户名
      - HALO_SECURITY_INITIALIZER_SUPERADMINUSERNAME=CasecoRI
      # 初始化的超级管理员密码
      - HALO_SECURITY_INITIALIZER_SUPERADMINPASSWORD=Coreeseeds14

  halodb:
    image: mysql:8.0.27
    container_name: halodb
    restart: on-failure:3
    networks:
      halo_network:
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysqlBackup:/data/mysqlBackup
    ports:
      - "3333:3333"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    environment:
      # 请修改此密码，并对应修改上方 Halo 服务的 SPRING_R2DBC_PASSWORD 变量值
      - MYSQL_ROOT_PASSWORD=Coreeseeds14@@
      - MYSQL_DATABASE=halo

networks:
  halo_network:
```

我创建了 MySQL 数据库，更改（因为被占用）并放行了端口，应该是哪里配置错了。
