### ISSUE TITLE
1.1.0-beta.1 使用docker-compose无法部署

### ISSUE THREAD

**Issue by JackyLeeCS** [halo-dev/halo#283]
升级到1.1.0-beta.1后，使用同样的docker-compose配置文件部署会报错，退回到1.0.3可以正常部署
```
Invalid initial heap size: -Xms${JVM_XMS}
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

我的docker-compose.yml的halo部分：
```yml
halo:
    restart: always
    image: ruibaby/halo:1.1.0-beta.1.dev
    container_name: halo
    ports:
      - 11111:11111
    environment:
      - MAX_UPLOAD_SIZE=10m
      - JVM_XMS=256m
      - JVM_XMX=512m
    depends_on:
      - mysql
    volumes:
      - ./data:/root/.halo
```
