### ISSUE TITLE
在开发环境下，无法通过配置 fixedPluginPath 添加新的插件

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2939]
### 是什么版本出现了此问题？

2.0.1

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://demo.halo.run

### 发生了什么？

配置如下：

```
halo:
  work-dir: ${user.home}/halo2-dev
  plugin:
    runtime-mode: development # development, deployment
    classes-directories:
      - "build/classes"
      - "build/resources"
    lib-directories:
      - "libs"
    fixedPluginPath:
      - "/Users/ryanwang/Workspace/github/ruibaby/halo-dev-plugins/plugin-migrate"
      - "/Users/ryanwang/Workspace/github/ruibaby/halo-dev-plugins/plugin-unsplash"
      - "/Users/ryanwang/Workspace/github/ruibaby/halo-dev-plugins/plugin-links"
      - "/Users/ryanwang/Workspace/github/ruibaby/halo-dev-plugins/plugin-sitemap"
      - "/Users/ryanwang/Workspace/github/ruibaby/halo-dev-plugins/plugin-comment-widget"
      - "/Users/ryanwang/Workspace/github/ruibaby/halo-dev-plugins/plugin-lightgallery"
      - "/Users/ryanwang/Workspace/github/ruibaby/halo-dev-plugins/plugin-highlightjs"
      - "/Users/ryanwang/Workspace/github/ruibaby/halo-dev-plugins/plugin-search-widget"
      - "/Users/ryanwang/Workspace/github/ruibaby/halo-dev-plugins/plugin-umami"
      - "/Users/ryanwang/Workspace/github/ruibaby/halo-dev-plugins/plugin-photos"
      - "/Users/ryanwang/Workspace/github/ruibaby/halo-dev-plugins/plugin-tui.editor"
      - "/Users/ryanwang/Workspace/github/ruibaby/halo-dev-plugins/plugin-live2d"
```

如上，后面三个为新加的插件，重启后无法加载成功，在 Console 列表没有展示：

<img width="1663" alt="image" src="https://user-images.githubusercontent.com/21301288/207328259-5bfbd896-d8c3-4604-897d-91215501000b.png">

清空数据库之后重启，可以加载成功：

<img width="1666" alt="image" src="https://user-images.githubusercontent.com/21301288/207328521-e7657cf8-225f-40d3-88c5-eae5310e9245.png">

/kind bug
/area core
