### ISSUE TITLE
扩展自定义元数据设置表单的设计

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#3005]
增加 AnnotationSetting 自定义模型用于保存模型 annotations 的 form schema，可以在使用时通过 targetRef 查询到一系列 formSchemas 进行特定资源扩展设置的表单渲染。

```yaml
apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  name: a-name
  labels: 
    # plugin.halo.run/plugin-name: fake-plugin
    theme.halo.run/theme-name: fake-theme
    halo.run/target-ref: posts.content.halo.run
spec:
  targetRef:
    group: content.halo.run
    kind: Post
  formSchema:
    - $formkit: text
      name: fancy.halo.run/download_url
      label: 下载链接
    - $formkit: select
      name: fancy.halo.run/version
      label: 支持的版本
      options:
        - value: "1.5"
          label: "1.5"
        - value: "2.0"
          label: "2.0"
```
如果为主题创建的用于文章使用的 annotations setting，文章使用时最终通过以上 setting 渲染的表单填写值后存储在 annotations 示例如下：
```yaml
apiVersion: content.halo.run/v1alpha1
kind: Post
metadata:
  annotations:
    fancy.halo.run/download_url: https://example.com/fake
    fancy.halo.run/version: "[\"1.5\", \"2.0\"]"
  creationTimestamp: '2022-12-15T09:45:36.089125Z'
  name: fake-post
spec:
  slug: hello-halo
  title: Hello Halo
  visible: PUBLIC
```

/cc @halo-dev/sig-halo

_Originally posted by @guqing in https://github.com/halo-dev/halo/issues/2858#issuecomment-1357204714_
