### ISSUE TITLE
主题和附件能够上传成功，但是均加载失败

### ISSUE THREAD

**Issue by twinkle255** [halo-dev/halo#3006]
### 是什么版本出现了此问题？

2.0.2

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://www.intpointer.com

### 发生了什么？

在使用nginx代理后，我的附件和主题能够上传成功，但是均加载失败。在服务器后台依然可以看到上传的主题和附件。使用ip＋端口号访问的时候还是正常的，用域名访问就不行。
另外这是在修改了`docker-compose.yaml`中的地址设置后才出现了这个问题。其余功能正常。

### 附加信息

`docker-compose.yaml`
```yaml
version: "3"

services:
  halo:
    image: halohub/halo:2.0.2
    container_name: halo
    restart: on-failure:3
    depends_on:
      halodb:
        condition: service_healthy
    networks:
      halo_network:
    volumes:
      - ./:/root/.halo2
    ports:
      - "8090:8090"
    environment:
      - SPRING_R2DBC_URL=r2dbc:pool:mysql://halodb:3306/halo
      - SPRING_R2DBC_USERNAME=root
      - VIRTUAL_HOST=www.intpointer.com
      - LETSENCRYPT_HOST=www.intpointer.com
      - MAX_UPLOAD_SIZE=10m
      - JVM_XMS=256m
      - JVM_XMX=1024m
      # MySQL 的密码，请保证与下方 MYSQL_ROOT_PASSWORD 的变量值一致。
      - SPRING_R2DBC_PASSWORD=
      - SPRING_SQL_INIT_PLATFORM=mysql
      # 外部访问地址，请根据实际需要修改
      - HALO_EXTERNAL_URL=https://www.intpointer.com/
      # 初始化的超级管理员用户名
      - HALO_SECURITY_INITIALIZER_SUPERADMINUSERNAME=
      # 初始化的超级管理员密码
      - HALO_SECURITY_INITIALIZER_SUPERADMINPASSWORD=

  halodb:
    image: mysql:8.0.27
    container_name: halodb
    restart: on-failure:3
    networks:
      halo_network:
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysqlBackup:/data/mysqlBackup
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    environment:
      # 请修改此密码，并对应修改上方 Halo 服务的 SPRING_R2DBC_PASSWORD 变量值
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=halo

networks:
  halo_network:
```
`nginx`配置
```conf
server {
  listen 80;
  listen [::]:80;
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  ssl_certificate /usr/local/nginx/conf/ssl/www.intpointer.com.crt;
  ssl_certificate_key /usr/local/nginx/conf/ssl/www.intpointer.com.key;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ecdh_curve X25519:prime256v1:secp384r1:secp521r1;
  ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256;
  ssl_conf_command Ciphersuites TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256;
  ssl_conf_command Options PrioritizeChaCha;
  ssl_prefer_server_ciphers on;
  ssl_session_timeout 10m;
  ssl_session_cache shared:SSL:10m;
  ssl_buffer_size 2k;
  add_header Strict-Transport-Security max-age=15768000;
  ssl_stapling on;
  ssl_stapling_verify on;
  server_name www.intpointer.com;
  access_log /data/wwwlogs/www.intpointer.com_nginx.log combined;
  index index.html index.htm index.php;
  root /data/wwwroot/www.intpointer.com;
  if ($ssl_protocol = "") { return 301 https://$host$request_uri; }
  
  include /usr/local/nginx/conf/rewrite/other.conf;
  #error_page 404 /404.html;
  #error_page 502 /502.html;
  location / {
    proxy_set_header HOST $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass http://halo;
  }
  location ~ .*\.(wma|wmv|asf|mp3|mmf|zip|rar|jpg|gif|png|swf|flv|mp4)$ {
    valid_referers none blocked *.intpointer.com www.intpointer.com;
    if ($invalid_referer) {
        return 403;
    }
  }
  location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|flv|mp4|ico)$ {
    proxy_pass http://halo;
    expires 30d;
    access_log off;
  }
  location ~ .*\.(js|css)?$ {
    proxy_pass http://halo;
    expires 7d;
    access_log off;
  }
  location ~ /(\.user\.ini|\.ht|\.git|\.svn|\.project|LICENSE|README\.md) {
    deny all;
  }
  location /.well-known {
    allow all;
  }
}

upstream halo {
  server 127.0.0.1:8090;
}
```
![屏幕截图 2022-12-19 173341](https://user-images.githubusercontent.com/95896306/208395372-38b0daa9-862e-465b-89e6-032eab43ea46.png)
![屏幕截图 2022-12-19 173409](https://user-images.githubusercontent.com/95896306/208395379-6029ba32-f337-457c-80ed-4794a22877aa.png)
