### ISSUE TITLE
能否在官网docker-compase安装教程中添加使用外部数据库的方法，试了很多次一直没有成功

### ISSUE THREAD

**Issue by maizi08** [halo-dev/halo#3336]
### Your current Halo version

2.2

### Describe this feature

能否在官网docker-compase安装教程中添加使用外部数据库的方法，试了很多次一直没有成功

**Comment by JohnNiang** [comment]
可以详细描述一下你的操作步骤。

/kind support

**Comment by maizi08** [comment]
配置使用阿里云4核8G服务器，外部数据库使用阿里云rds mysql数据库
![Uploading 8823182E-6F5A-4F23-A87F-19BE6E58704F.jpeg…]()

**Comment by shiker1996** [comment]
你是容器连容器所在主机吧，可以参考docker官方文档看下容器网络设置

**Comment by wxyShine** [comment]
`docker-compose.yaml`
```yml
version: "3"

services:
    halo:
        image: halohub/halo:2.2.1
        container_name: halo
        restart: on-failure:3
        network_mode: "host"
        volumes:
            - ./:/root/.halo2
        command:
          - --spring.r2dbc.url=r2dbc:pool:mysql://127.0.0.1:3306/halo
          - --spring.r2dbc.username=root
          # MySQL 的密码，请保证与下方 MYSQL_ROOT_PASSWORD 的变量值一致。        
          - --spring.r2dbc.password=mima
          - --spring.sql.init.platform=mysql
          # 外部访问地址，请根据实际需要修改          - --halo.external-url=http://127.0.0.1:8090/
          # 初始化的超级管理员用户名          - --halo.security.initializer.superadminusername=halo
          # 初始化的超级管理员密码          - --halo.security.initializer.superadminpassword=halo
```
