### ISSUE TITLE
元数据表单定义的默认值不生效

### ISSUE THREAD

**Issue by LIlGG** [halo-dev/halo#3357]
### 是什么版本出现了此问题？

2.2.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

1. 编写主题时，使用元数据表单定义一个 checkbox 元数据，并赋予默认值 `value: true` 或 `value: "true"`.
2. 在 console 端，该元数据未被默认勾选。

预计正确情况应该是该元数据会被默认勾选。

附元数据配置：
```yaml
apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  generateName: annotation-setting-
spec:
  targetRef:
    group: content.halo.run
    kind: Post
  formSchema:
    - $formkit: "checkbox"
      name: "randomImage"
      label: "使用随机图"
      value: "true"
```

### 附加信息

![image](https://user-images.githubusercontent.com/31335418/220312675-cca8f3c9-6e6a-46c3-82e1-bc51ee8ec608.png)
