### ISSUE TITLE
为什么配置了yaml文件地址 显示的默认外部地址还是http://localhost:8090？如何修改？

### ISSUE THREAD

**Issue by luming0616** [halo-dev/halo#3399]
### What is version of Halo has the issue?

2.2

### What database are you using?

MySQL 8.x

### What is your deployment method?

Docker Compose

### What happened?

概览里的默认外部访问地址还是http://localhost:8090，但是配置文件已经配置了
![image](https://user-images.githubusercontent.com/125715471/221362622-e4f5394d-0949-4f6b-a929-7ab0abee57da.png)

### Additional information

```yaml
version: "3"

services:
  halo:
    image: halohub/halo:2.2.0
    container_name: halo
    restart: on-failure:3
    depends_on:
      halodb:
        condition: service_healthy
    networks:
      halo_network:
    volumes:
      - ./:/root/.halo2
    ports:
      - "8090:8090"
    command:
      - spring.r2dbc.url=r2dbc:pool:mysql://halodb:3306/halo
      - spring.r2dbc.username=root
      # MySQL 的密码，请保证与下方 MYSQL_ROOT_PASSWORD 的变量值一致。
      - spring.r2dbc.password=123321
      - spring.sql.init.platform=mysql
      # 外部访问地址，请根据实际需要修改
      - halo.external-url=http://43.139.116.61:8090/
      # 初始化的超级管理员用户名
      - halo.security.initializer.superadminusername=admin
      # 初始化的超级管理员密码
      - halo.security.initializer.superadminpassword=qianqian0616

  halodb:
    image: mysql:8.0.31
    container_name: halodb
    restart: on-failure:3
    networks:
      halo_network:
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --explicit_defaults_for_timestamp=true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysqlBackup:/data/mysqlBackup
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    environment:
      # 请修改此密码，并对应修改上方 Halo 服务的 SPRING_R2DBC_PASSWORD 变量值
      - MYSQL_ROOT_PASSWORD=123321
      - MYSQL_DATABASE=halo

networks:
  halo_network:
```
