### ISSUE TITLE
支持配置集成第三方登录（OAuth）

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3423]
### 你当前使用的版本

2.3.0

### 描述一下此特性

期望 Halo 能够提供配置和集成第三方登录，并且支持通过插件来扩展登录来源，具体支持建议：

1. Halo 本身可以不集成任何第三方登录，Halo 核心仅提供入口和拓展。
2. 期望在一个统一的配置页面来配置第三方登录。
3. 用户支持绑定和解绑已配置的登录来源。

**Comment by ruibaby** [comment]
流程可以参考我们目前使用的论坛系统（Flarum）：

来源配置：

<img width="1341" alt="image" src="https://user-images.githubusercontent.com/21301288/221797591-0a42ecf5-659d-4c95-9121-68f6da90faf4.png">

登录：

<img width="382" alt="image" src="https://user-images.githubusercontent.com/21301288/221797680-67e54768-7199-42ed-a9c1-b84f1da39bd6.png">

解除绑定：

<img width="653" alt="image" src="https://user-images.githubusercontent.com/21301288/221797791-75cb7086-62ef-4890-b873-41cb087abacd.png">

**Comment by guqing** [comment]
1. 通过定义一个 Extension 来添加一种认证方式，示例数据如下：
```yaml
apiVersion: auth.halo.run/v1alpha1
kind: AuthProvider
metadata:
  name: github
spec:
  displayName: GitHub
  description: GitHub Inc. is a web-based hosting service for version control using Git.
  logo: https://github.com/logo.png
  website: https://github.com
  enabled: true
  helpPage: https://github.com/oauth2/help
  authenticationUrl: /oauth2/authorization/github
  settingRef:
    name: generic-oauth-setting
    group: github
  configMapKeyRef:
    name: generic-oauth-configmap
    key: github
```
Console 可以通过列出 AuthProvider 中 spec.enabled=true 的数据展示到登录页面
2. 增加一个扩展点 AdditionalWebFilter
