### ISSUE TITLE
密码错误

### ISSUE THREAD

**Issue by flyondog** [halo-dev/halo#3523]
### 是什么版本出现了此问题？

2.3

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

登陆密码总是不对，使用以下命令安装，登陆密码不对，改了我自己的密码页不行，我删除docker容器、镜像，删除  -v ~/.halo2:/root/.halo2 \，终于可以登陆了，过来几个小时之后，登陆密码又不对了。我用bitwarden记住密码，密码肯定不会错。

```
docker run \
  -it -d \
  --name halo \
  -p 8090:8090 \
  -v ~/.halo2:/root/.halo2 \
  halohub/halo:2.3.0 \
  --halo.external-url=http://localhost:8090/ \
  --halo.security.initializer.superadminusername=admin \
  --halo.security.initializer.superadminpassword=P@88w0rd  
```
我使用这个命令安装的。

### 相关日志输出

```shell
docker logs halo | grep 'Generated random password:' | tail -1
使用这个指令不会输出密码
```

### 附加信息

root@ubuntu:~# docker logs halo2 | grep 'Generated random password:' | tail -1
root@ubuntu:~# docker logs halo2 | grep 'Generated random password:' | tail -1
root@ubuntu:~# docker logs halo2 | grep 'Generated random password:' | tail -1
root@ubuntu:~# docker logs halo2 | grep 'Generated random password:' | tail -1
root@ubuntu:~# docker logs halo2 | grep 'Generated random password:' | tail -1

**Comment by laodao** [comment]
我也是一样的问题。

**Comment by ruibaby** [comment]
/kind support

> 过来几个小时之后，登陆密码又不对了

没有想到有什么样的可能会导致这样的问题。

/cc @halo-dev/sig-halo

**Comment by zhengskty** [comment]
一样的问题，官方文档的docker安装就回出现密码错误

**Comment by ruibaby** [comment]
我这边尝试之后未复现，我这里提供几种可能：

1. 挂载的目录之前已经有数据，所以初始化用户名和密码的变量不会再有用。
2. 命令格式问题导致密码字符串不正确。

**Comment by zhengskty** [comment]
昨天使用的centos steam版本以docker方式安装halo会出现密码错误，今天换成ubuntu就一切正常了

**Comment by Wh1tew0lf-sea** [comment]
问题相同，已经删了好多个container了

**Comment by JohnNiang** [comment]
> 问题相同，已经删了好多个container了

密码错误问题删除 container 是不起作用的。要么删除 `/root/.halo2` 所对应挂载的文件，要么删除数据库。

**Comment by huqay** [comment]
碰到同样的问题，不过我用的时Windows

**Comment by wuxiaobai137** [comment]
这个问题是无解了吗？docker、docker-compose都试了下，全是密码错误，，，

**Comment by ruibaby** [comment]
> 这个问题是无解了吗？docker、docker-compose都试了下，全是密码错误，，，

无法密码错误的问题，无论是 Docker 或者是 Compose。你可以提供你 docker run 的命令和 docker-compose.yaml 文件的内容，我们看看是否能够复现。

**Comment by wuxiaobai137** [comment]
> 

```
version: '2.4'
services:
  halo: 
    image: 'halohub/halo:2.4.0'
    container_name: halo
    restart: 'on-failure:3'
    network_mode: host
    volumes:
      - './:/root/.halo2'
    command:
      - spring.r2dbc.url=r2dbc:pool:mysql://localhost:3306/halo
      - spring.r2dbc.username=root
      - spring.r2dbc.password=Aa123456
      - spring.sql.init.platform=mysql
      - halo.external-url=http://localhost:8090/
      - halo.security.initializer.superadminusername=admin
      - halo.security.initializer.superadminpassword=P@88w0rd  
      - server.port=8090
networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.159.0/24
    name: my-network

```

这是我的docker-compose文件，部署在腾讯云服务器上，Mysql版本是5.7.36
（刚在论坛上有个兄弟提到，密码后面加2个空格，但遗憾没有起作用）

刚看了下数据库，一张表都没有，这个情况是否正常？
![image](https://user-images.githubusercontent.com/130144320/231187607-cb99d587-4945-4676-882e-7fbbb50435cf.png)
