### ISSUE TITLE
希望 RoleBinding 支持绑定其他 Role

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#3560]
### Your current Halo version

latest

### Describe this feature

希望 RoleBinding 支持绑定其他 Role，比如：
```yaml
apiVersion: v1alpha1
kind: RoleBinding
metadata:
  name: rolebinding-authenticated-plugin-oauth
roleRef:
  kind: Role
  name: plugin-oauth-role-template
subjects:
  - kind: Role
    name: authenticated
```
这样就可以将 `plugin-oauth-role-template` 聚合到现有角色 `authenticated`，比如插件中想要将插件实现的 API 让所有已登录用户访问时这很有用

### Additional information

/kind feature
/milestone 2.4.x
/area core
