### ISSUE TITLE
使用docker和docker-compose部署会导致后台无法登陆（问题已解决只是反馈一下bug）

### ISSUE THREAD

**Issue by huaizhu1** [halo-dev/halo#3590]
### 是什么版本出现了此问题？

最新版本

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

我在尝试两种部署方法默认部署后都发现使用公网ip进入后台时都会提示密码错误，但使用域名反带加上更改了外部访问地址之后就能正常访问了，这个应该是个bug，对新用户不友好，基础的展示版本后台无法访问估计能劝退好一部分新人，希望作者大大修复或者表明一下

```
version: "3"

services:
  halo:
    image: halohub/halo:2.3.0
    container_name: halo
    restart: on-failure:3
    volumes:
      - ./:/root/.halo2
    ports:
      - "8090:8090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health/readiness"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s          
    command:
      # 外部访问地址，请根据实际需要修改
      - --halo.external-url=http://localhost:8090/
      # 初始化的超级管理员用户名
      - --halo.security.initializer.superadminusername=admin
      # 初始化的超级管理员密码
      - --halo.security.initializer.superadminpassword=P@88w0rd
```
