### ISSUE TITLE
增加隐性URL解析设置功能

### ISSUE THREAD

**Issue by own5464** [halo-dev/halo#3605]
### 你当前使用的版本

2.3.2

### 描述一下此特性

Halo 默认不能使用 iframe ，希望能增加iframe自定义设置，以实现隐性URL解析

### 附加信息

无

**Comment by JohnNiang** [comment]
/kind feature
/area core

为了安全，默认仅支持同源网站使用 iframe 引用 Halo。不过一些特殊场景，确实需要放开此限制，例如[隐性 URL](https://cloud.tencent.com/document/product/302/12649)。

我建议增加配置项来控制此行为，例如：

```yaml
halo:
  security:
    frame-options:
      disabled: true | false
      mode: deny | sameorigin
```
