### ISSUE TITLE
为访客端提供一套完整的 API

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3661]
### 你当前使用的版本

2.4.0

### 描述一下此特性

目前 Halo 虽然和前端（Console）的交互都是使用的 API，但目前针对于访客端提供的 API 有限，期望能够提供一套完整的 API 以供访客端使用，可以用于构建：

1. SPA 程序（Vue，React 等）
2. 小程序
3. SSG 框架（Astro、Nuxt.js 等）
4. SSR 框架（Nuxt.js、Next.js 等）

/area core
/milestone 2.5.x
/kind feature

**Comment by BenanaH** [comment]
期待

**Comment by guqing** [comment]
期望根据配置自动生成 public get and list APIs:
```yaml
kind: ExtensionPublicAPIGeneratorConfig
metadata:
  name: post-publi-api-generator
spec:
  extensions:
  - group: content.halo.run
    version: v1alpha1
    names:
      kind: Post
      plural: posts
    apis:
      - name: list-posts
        path: /posts #/apis/api.{group}/{version}/posts
        method: GET
        query: 
          # 默认的查询条件，会被覆盖
          labelSelector: content.halo.run/owner=guqing, content.halo.run/archive-year=2023
          limit: 20
          sort: "spec.publishTime,desc"
        response:
          type: PostList
        filters:
         # 用于生成 Predicate 和 Comparator
          - name: visibilityExpression
            description: Adjust spec.visible based on authentication and login status.
            type: string
            required: false
            default: "PUBLIC"
            expression: "if (context.loggedIn) { return [\"PUBLIC\", \"INTERNAL\"] } else {return [\"PUBLIC\"]}"
          - name: publishedLabelSelector
            description: Label selector for listing posts: must contains published label and value must be true
            labelRequirement:
              - key: content.halo.run/published
                operator: EQ
                values:
                  - "true"
          - name: deletedFieldSelector
            description: Label selector for listing posts: must contains published label and value must be true
            fieldRequirement:
              - key: spec.deleted
                operator: EQ
                type: boolean
                values:
                  - false
        sort:
          - key: spec.publishTime
            desc: true
```
