### ISSUE TITLE
mysql作为存储引擎没有业务表

### ISSUE THREAD

**Issue by yankooo** [halo-dev/halo#3716]
### What is version of Halo has the issue?

mysql作为存储引擎没有业务表

### What database are you using?

H2

### What is your deployment method?

Docker

### What happened?

用compose部署，按理说halo库应该都会初始化表，但是竟然只有一张拓展表。
```yaml
version: "3"

services:
  halo:
    image: halohub/halo:2.4
    container_name: halo
    restart: on-failure:3
    depends_on:
      halodb:
        condition: service_healthy
    networks:
      halo_network:
    volumes:
      - ./:/root/.halo2
    ports:
      - "8090:8090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health/readiness"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    command:
      - --spring.r2dbc.url=r2dbc:pool:mysql://halodb:3306/halo
      - --spring.r2dbc.username=root
      # MySQL 的密码，请保证与下方 MYSQL_ROOT_PASSWORD 的变量值一致。
      - --spring.r2dbc.password=q
      - --spring.sql.init.platform=mysql
      # 外部访问地址，请根据实际需要修改
      - --halo.external-url=https://www.bitbo-liuyang.com/
      # 初始化的超级管理员用户名
      - --halo.security.initializer.superadminusername=m
      # 初始化的超级管理员密码
      - --halo.security.initializer.superadminpassword=q

  halodb:
    image: mysql:8.0.31
    container_name: halodb
    restart: on-failure:3
    networks:
      halo_network:
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --explicit_defaults_for_timestamp=true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysqlBackup:/data/mysqlBackup
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    environment:
      # 请修改此密码，并对应修改上方 Halo 服务的 SPRING_R2DBC_PASSWORD 变量值
      - MYSQL_ROOT_PASSWORD=q
      - MYSQL_DATABASE=halo

  ngx:
    container_name: halongx
    image: nginx
    networks:
      halo_network:
    ports:
      - '80:80'              # 不建议修改端口
      - '443:443'            # 不建议修改端口
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs/access.log:/var/log/nginx/access.log
      - ./nginx/logs/error.log:/var/log/nginx/error.log
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /opt/pic:/opt/pic
      - ./nginx/ssl:/usr/local/nginx/ssl

networks:
  halo_network:
```

<img width="618" alt="image" src="https://user-images.githubusercontent.com/31951382/230615503-3cafb296-e53b-49d0-af0f-5b16e112a10c.png">
