### ISSUE TITLE
Request to group OpenAPI dynamically instead of pre-defined

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#3828]
### Your current Halo version

2.5.0-SNAPSHOT

### Describe this feature

Currently, we have defined several groups in source code, it's very unreasonable, especially for APIs provided by plugins.

```json
{
  "configUrl": "/v3/api-docs/swagger-config",
  "oauth2RedirectUrl": "http://localhost:8090/webjars/swagger-ui/oauth2-redirect.html",
  "urls": [
    {
      "url": "/v3/api-docs/all-api",
      "name": "All APIs"
    },
    {
      "url": "/v3/api-docs/api.halo.run",
      "name": "api.halo.run"
    },
    {
      "url": "/v3/api-docs/core-api",
      "name": "Core APIs"
    },
    {
      "url": "/v3/api-docs/core-custom-api",
      "name": "Custom APIs in Core"
    },
    {
      "url": "/v3/api-docs/extension-api",
      "name": "Extension APIs"
    },
    {
      "url": "/v3/api-docs/plugin-custom-api",
      "name": "Custom APIs in Plugin"
    }
  ],
  "validatorUrl": ""
}
```

So I suggest grouping OpenAPI by API group. e.g.:

```yaml
springdoc:
  group-configs:
    - group: halo.run
      paths-to-match: /api/**
    - group: content.halo.run
      paths-to-match: /apis/content.halo.run/**
    - group: storage.halo.run
      paths-to-match: /apis/storage.halo.run/**
    - group: app.halo.run
      paths-to-match: /apis/app.halo.run/**
    - group: api.halo.run
      paths-to-match: /apis/api.halo.run/**
    - group: api.console.halo.run
      paths-to-match: /apis/api.console.halo.run/**
    - group: api.plugin.halo.run
      paths-to-match: /apis/api.plugin.halo.run/**
    - group: all
      display-name: All APIs(Only for development)
      paths-to-match: /api/**,/apis/**
```

This approach is from <https://springdoc.org/v2/#how-can-i-define-groups-using-application-yml>.

### Additional information

/kind improvement
/area core
