### ISSUE TITLE
统一插件和主题描述文件的部分字段

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#4011]
### 你当前使用的版本

2.6.0-SNAPSHOT

### 描述一下此特性

目前发现主题和插件的模型有一部分字段有些差异，建议这些字段可以统一一下。

主题的 `theme.yaml`:

```yaml
apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: halo-theme-official-v3
spec:
  displayName: Official V3
  author:
    name: Halo OSS Organization
    website: https://halo.run
  description: Halo 官网主题 V3
  logo: https://halo.run/logo
  website: https://github.com/f2ccloud/halo-theme-official-v3
  repo: https://github.com/f2ccloud/halo-theme-official-v3.git
  settingName: "halo-theme-official-v3-setting"
  configMapName: "halo-theme-official-v3-configMap"
  version: 1.0.8
  requires: ">=2.4.0"
```

插件的 `plugin.yaml`:

```yaml
apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: plugin-oauth2
spec:
  enabled: true
  version: "1.0.2"
  requires: ">=2.4.0"
  author:
    name: Halo OSS Team
    website: https://github.com/halo-dev
  logo: logo.svg
  homepage: https://github.com/halo-sigs/plugin-oauth2
  displayName: "OAuth2 认证"
  description: "提供 OAuth2 认证方式"
  license:
    - name: "MIT"
```

问题如下：

1. 关于网站的字段不同，主题是 website，而插件是 homepage。
2. 主题没有 license。
3. 插件没有 repo。

/area core
/kind api-change
/kind improvement
