### ISSUE TITLE
刷新页面缓存的接口需要添加角色模板

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#4143]
### 你当前使用的版本

2.7.0-rc.1

### 描述一下此特性

Halo 在 https://github.com/halo-dev/halo/pull/4091 中提供了页面静态缓存的功能，并提供了刷新缓存的接口和功能按钮，但目前此接口没有定义角色模板和 UI 权限，所以任何角色的用户在 Console 都可以看到刷新页面缓存的按钮和调用。所以期望为此接口添加角色模板。

<img width="693" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/a808609a-b07f-4401-921a-1016e5ad6358">

/kind improvement
/area console
/area core
/milestone 2.7.x

**Comment by JohnNiang** [comment]
想要实现权限的分配，可能需要创建新的权限模板，请看下面的示例：

```yaml
apiVersion: v1alpha1
kind: "Role"
metadata:
  name: role-template-manage-cache
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "Cache Management"
    rbac.authorization.halo.run/display-name: "Cache Manage"
    rbac.authorization.halo.run/ui-permissions: |
      ["system:cache:manage"]
rules:
  - apiGroups: ["api.console.halo.run"]
    resources: ["caches"]
    verbs: ["delete"]
```

Hi @ruibaby ，有什么建议或意见么？
