### ISSUE TITLE
修改页面缓存配置字段

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#4144]
### 你当前使用的版本

2.7.0-rc.1

### 描述一下此特性

Halo 在 https://github.com/halo-dev/halo/pull/4091 中提供了页面静态缓存的功能，并默认关闭，如果需要开启，需要添加以下配置：

```yaml
halo:
  cache:
    disabled: true
```

但这样可能从字面意思上比较宽泛，如果直接看配置可能无法知道是页面缓存的开关，建议使用以下方式：

```yaml
halo:
  cache:
    page:
      disabled: true
```
