### ISSUE TITLE
如何修改 administrator 登录过期时间

### ISSUE THREAD

**Issue by yuanzhixiang** [halo-dev/halo#4163]
### 是什么版本出现了此问题？

2.6.0

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 发生了什么？

登录 administrator 后过期时间太短了，挂一会儿就需要重新登录，如何修改过期时间？

**Comment by guqing** [comment]
如果使用配置文件则修改在 application.yaml 添加：
```yaml
server:
  reactive:
    session:
      timeout: 1h # 1小时过期
```
如果是使用命令行参数配置如 https://docs.halo.run/getting-started/install/docker-compose 可以在 command 上加上一行
```
- --server.reactive.session.timeout=1h
```
