### ISSUE TITLE
在Setting表单的repeater组件中不能正常使用条件判断

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#4603]
### 是什么版本出现了此问题？

v2.9.1

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

在主题设置中使用 repeater 组件时，希望同一组配置项中某些内容根据前面配置的值判断是否显示，如果采用 `$get(id).value` 的方式进行判断，添加多组配置时会出现重复 id 导致无法正常判断。

例如使用下面的配置文件，期望下拉选择 a 时才显示输入框，但当 repeater 中添加多个条目时不能正常处理。
```yaml
apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-tailblocks-setting
spec:
  forms:
    - group: test
      label: 测试
      formSchema:
        - $formkit: repeater
          name: items
          value: []
          children:
            - $formkit: select
              name: select1
              id: select1
              label: 下拉
              options:
                - value: a
                  label: a
                - value: b
                  label: b
            - $formkit: text
              if: "$get(select1).value === a"
              name: input1
              id: input1
              label: 输入
```
![image](https://github.com/halo-dev/halo/assets/27671436/04c99dee-1f31-4e89-9371-dbf09bb1b7f4)
