### ISSUE TITLE
ReactiveSettingFetcher在2.10中会出现类型转换错误异常

### ISSUE THREAD

**Issue by DioxideCN** [halo-dev/halo#4727]
### 是什么版本出现了此问题？

2.10

### 使用的什么数据库？

H2

### 使用的哪种方式运行？

Source Code

### 发生了什么？

```java
@Slf4j
@Component
@AllArgsConstructor
public class GraphQLReader {

    private final ReactiveSettingFetcher settingFetcher;

    @Resource
    private ToolBenchPlugin PLUGIN;

    @NotNull
    public Mono<JsonNode> executeQuery(String owner, String repo, BiFunction<String, String, String> queryBuilder) {
        return this.settingFetcher.get("basic")
                .map(setting -> setting.get("githubToken").asText("Github Token"))
                .defaultIfEmpty("Github Token")
                .flatMap(token -> WebClient.builder()
                        .baseUrl("https://api.github.com/graphql")
                        .defaultHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE)
                        .defaultHeader(HttpHeaders.AUTHORIZATION, "token " + token)
                        .build()
                        .post()
                        .bodyValue(Map.of(
                                "query", queryBuilder.apply(owner, repo)
                        ))
                        .retrieve()
                        .bodyToMono(String.class))
                .flatMap(jsonString -> {
                    try {
                        final ObjectMapper objectMapper = new ObjectMapper();
                        JsonNode jsonNode = objectMapper.readTree(jsonString);
                        return Mono.just(jsonNode);
                    } catch (Exception e) {
                        return Mono.empty();
                    }
                });
    }

}
```

如上的代码作用是通过`ReactiveSettingFetcher`去获取`basic` group的配置信息，其中`this.settingFetcher.get("basic")`必然返回一个`Mono<JsonNode>`但是在2.10版本以后这个转换过程发生了异常。异常情况为无法从`ObjectNode`转换到`JsonNode`。

在2.10版本以前不存在这个问题，同时已经通过Logger系统排除了代码错误和配置错误的可能，在2.10以后是否相关的API发生了更新？需要变更获取配置信息的方法？

### 相关日志输出

```shell
2023-10-15T10:59:11.127+08:00 ERROR 25616 --- [ctor-http-nio-2] a.w.r.e.AbstractErrorWebExceptionHandler : [c977e1ad-9]  500 Server Error for HTTP GET "/apis/api.plugin.halo.run/v1alpha1/plugins/ToolBench/github/repository?owner=jiewenhuang&repo=halo-theme-macwen"

java.lang.ClassCastException: class com.fasterxml.jackson.databind.node.ObjectNode cannot be cast to class com.fasterxml.jackson.databind.JsonNode (com.fasterxml.jackson.databind.node.ObjectNode is in unnamed module of loader 'app'; com.fasterxml.jackson.databind.JsonNode is in unnamed module of loader org.pf4j.PluginClassLoader @2ab630ad)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106) ~[reactor-core-3.5.10.jar:3.5.10]
```

### 附加信息

以下是`settings.yaml`的部分配置信息：
```yaml
apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-tool-bench-settings
spec:
  forms:
    - group: basic
      label: 通用设置
      formSchema:
        - $formkit: text
          label: 目录页标题
          name: directory
          validation: required
          value: "目录"
        - $formkit: text
          label: 目录页副标题
          name: directorySubContent
          validation: required
          value: "目录页将按所有文章的分类进行排序展示"
```
