### ISSUE TITLE
希望暴露出 actuator metrics 指标以提高 halo 的可观测性

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#4894]
### Your current Halo version

2.10.2

### Describe this feature

目前 Halo 在生产模式下只提供了 `["health", "info", "startup", "globalinfo", "logfile", "shutdown", "restart"]` 这些 actuator endpoint, 希望能暴露如 metrics 指标数据并加入 micrometer-registry-prometheus 以便能够使用 prometheus 抓取指标数据对 halo 进行服务监控

### Additional information

/kind feature
/area core
/milestone 2.11.x

**Comment by guqing** [comment]
貌似不需要引入 `micrometer-registry-prometheus` 如果有需要或可使用插件提供对应功能，比如 [AppOptics](https://micrometer.io/docs/registry/appOptics)，[Atlas](https://micrometer.io/docs/registry/atlas)，[datadoghq](https://www.datadoghq.com/)，[Influx](https://micrometer.io/docs/registry/influx)，[OpenTelemetry](https://micrometer.io/docs/registry/otlp)，[Prometheus](https://micrometer.io/docs/registry/prometheus) 等，需要什么就由插件去添加即可

**Comment by JohnNiang** [comment]
Hi @guqing ，如果想要暴露更多的 Actuator Endpoints，可以通过以下配置的方式配置即可：

```yaml
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "startup", "globalinfo", "logfile", "shutdown", "restart", "metrics"]
```

可能需要提供一个角色来决定是否可访问这些 endpoints。
