### ISSUE TITLE
Request to build a new formkit component for creating secrets

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#5094]
### Your current Halo version

2.12.0-SNAPSHOT

### Describe this feature

I have checked official documentation about Formkit components at <https://docs.halo.run/developer-guide/form-schema>, but there is no secret-related component.

If we supported that component, [the secret logic](https://github.com/halo-dev/plugin-app-store/blob/9e7bd053713344235c095f51254fbfdc8d948b6f/console/src/components/plugin-tabs/AccountBindingTab.vue#L76-L89) in app-store plugin could be greatly simplified.

Example:

```yaml
$formkit: secret
name: app-store
label: App Store
permissions: uc:app-store.secret:manage
```

Please note the `permissions` above example, we need to check if the current user has enough permissions to manage secrets.

### Additional information

/kind feature
/area console
