### ISSUE TITLE
在设置表单 repeater 中使用 select、if 和 group 的组合最终设置值错误

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#5179]
### 系统信息

- 外部访问地址: http://localhost:8090/
- 启动时间: 2024-01-11 06:48
- 版本: 2.11.1
- 构建时间: 2023-12-02 22:53
- Git Commit: 54f77d5
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: PostgreSQL / 15.3 (Debian 15.3-1.pgdg120+1)
- 操作系统: Linux / 5.15.133.1-microsoft-standard-WSL2
- 已激活主题: Blocks
- 已启动插件:
  - [代码注入增强插件](https://github.com/halo-sigs/plugin-codeInjection)
  - [社交 IAM 认证](https://github.com/f2ccloud/plugin-social-login)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - AI 助手
  - [文章限制阅读 Pro](https://github.com/f2ccloud/plugin-restricted-reading-pro)
  - [Docsme](https://github.com/f2ccloud/plugin-docsme)
  - [KaTeX](https://github.com/halo-sigs/plugin-katex)
  - 联系表单
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [应用市场服务端](https://github.com/f2ccloud/plugin-app-store-server)
  - [WangEditor](https://gitee.com/handsome-npc/halo-wangEditor-plugin)
  - [微信公众号发布](https://github.com/f2ccloud/plugin-platforms-sync)
  - [站点迁移](https://github.com/halo-sigs/plugin-migrate)
  - [StackEdit](https://github.com/halo-sigs/plugin-stackedit)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [Sitemap](https://github.com/halo-sigs/plugin-sitemap)
  - [Unsplash](https://github.com/halo-sigs/plugin-unsplash)
  - [reveal.js 幻灯片编辑器](https://github.com/wan92hen/plugin-revealjs)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [RSS](https://github.com/halo-sigs/plugin-feed)
  - [评论组件](https://github.com/halo-sigs/plugin-comment-widget)
  - [搜索组件](https://github.com/halo-sigs/plugin-search-widget)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)

### 使用的哪种方式运行？

Docker

### 发生了什么？

使用类似下面的主题设置：
```
spec:
  forms:
    - group: index
      label: 首页配置
      formSchema:
        - $formkit: repeater
          name: blocks
          label: 内容块
          children:
            - $formkit: select
              name: name
              label: 名称
              options:
                - label: block1
                  value: block1          
                - label: block2
                  value: block2          
                - label: block3
                  value: block3
            - $formkit: group
              name: block1_config
              if: $value.name === "block1"
              label: 块1配置
              children:
                - $formkit: text
                  name: title1
                  label: 块1标题
                  value: "块1标题"
            - $formkit: group
              name: block2_config
              if: $value.name === "block2"
              label: 块2配置
              children:
                - $formkit: text
                  name: title2
                  label: 块2标题
                  value: "块2标题"              
                - $formkit: url
                  name: url2
                  label: 块2链接
                  value: "块2链接"
```
![image](https://github.com/halo-dev/halo/assets/27671436/1ca60389-c6b2-4559-b01f-fecaaef6efa9)
页面上进行类似上面的配置保存后，得到的结果 `theme.config.index.blocks` 有误，当前值为：
```
[{"name":"block1","block1_config":{"title1":"块1标题"}},{"name":"block2","block1_config":{"title1":"块1标题","url2":"块2链接"}}]
```
正确值应该是：
```
[{"name":"block1","block1_config":{"title1":"块1标题"}},{"name":"block2","block2_config":{"title2":"块2标题","url2":"块2链接"}}]
```
