### ISSUE TITLE
使用 WSL2 Debian12 Docker Compose 部署 Halo 出现 JVMCFRE076 bad magic number

### ISSUE THREAD

**Issue by lkc1009-ars** [halo-dev/halo#5185]
### 系统信息

操作系统：Windows WSL2 Debian12 / 5.15.133.1-microsoft-standard-WSL2
Docker Version：Docker version 20.10.24+dfsg1, build 297e128
Docker Compose：docker-compose version 1.29.2, build unknown / Docker Compose version v2.23.3-desktop.2 （PS：尝试更换过一次版本）

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

使用 WSL2 Debian12 Docker Compose 进行部署

使用官网文档中的 Docker Compose 的配置文件 （Halo + MySQL）
```yml
version: "3"

services:
  halo:
    image: halohub/halo:2.11
    container_name: halo
    restart: on-failure:3
    depends_on:
      halodb:
        condition: service_healthy
    networks:
      network:
    volumes:
      - /home/lkc1009/docker/halo2/.halo2:/root/.halo2
    ports:
      - "8090:8090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health/readiness"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    command:
      - --spring.r2dbc.url=r2dbc:pool:mysql://halodb:3306/halo
      - --spring.r2dbc.username=root
      # MySQL 的密码，请保证与下方 MYSQL_ROOT_PASSWORD 的变量值一致。
      - --spring.r2dbc.password=o#DwN&JSa56
      - --spring.sql.init.platform=mysql
      # 外部访问地址，请根据实际需要修改
      - --halo.external-url=http://localhost:8090/

  halodb:
    image: mysql:8.1.0
    container_name: halodb
    restart: on-failure:3
    networks:
      network:
    command: 
      - --default-authentication-plugin=caching_sha2_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --explicit_defaults_for_timestamp=true
    volumes:
      - /home/lkc1009/docker/halo2/mysql:/var/lib/mysql
      - /home/lkc1009/docker/halo2/mysqlBackup:/data/mysqlBackup
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    environment:
      # 请修改此密码，并对应修改上方 Halo 服务的 SPRING_R2DBC_PASSWORD 变量值
      - MYSQL_ROOT_PASSWORD=o#DwN&JSa56
      - MYSQL_DATABASE=halo

networks:
  network:
```

部署后 Halo 出现 （MYSQL 正常启动）
```
Error: LinkageError occurred while loading main class org.springframework.boot.loader.launch.JarLauncher
java.lang.ClassFormatError: JVMCFRE076 bad magic number; class=org/springframework/boot/loader/launch/JarLauncher, offset=0
```

### 相关日志输出

```shell
Error: LinkageError occurred while loading main class org.springframework.boot.loader.launch.JarLauncher
	java.lang.ClassFormatError: JVMCFRE076 bad magic number; class=org/springframework/boot/loader/launch/JarLauncher, offset=0
```
