### ISSUE TITLE
使用 MariaDB 有几率无法正常初始化 Halo

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#5534]
### 系统信息

None

### 使用的哪种方式运行？

Docker

### 发生了什么？

在初始化数据时，会遇到接口一直 pending 的问题。

<img width="1470" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/4285e684-8d61-4f69-83ec-042d83d46fd1">

Ref https://bbs.halo.run/d/5193-docker-compose-部署初始化时提示网络错误/12

日志：[halo.log](https://github.com/halo-dev/halo/files/14681216/halo.log)

### 附加信息

我的 Docker Compose 文件：

```yaml
version: "3"

services:
  halo:
    image: halohub/halo:2.13
    restart: on-failure:3
    networks:
      halo_network:
    volumes:
      - ./halo2:/root/.halo2
    ports:
      - "8090:8090"
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:8090/actuator/health/readiness"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    command:
      - --spring.r2dbc.url=r2dbc:pool:mariadb://halodb:3306/halo
      - --spring.r2dbc.username=root
      - --spring.r2dbc.password=o#DwN&JSa56
      - --spring.sql.init.platform=mysql
      - --halo.external-url=http://localhost:8090/

  halodb:
    image: mariadb
    restart: on-failure:3
    networks:
      halo_network:
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=o#DwN&JSa56
      - MARIADB_DATABASE=halo

networks:
  halo_network:
```
