### ISSUE TITLE
主题开发时settings.yaml配置文件怎么能够在列表里按条件去做动态配置

### ISSUE THREAD

**Issue by kecikeci** [halo-dev/halo#6289]
### 你当前使用的版本

2.17.1

### 描述一下此特性

```
        - $formkit: list
          name: index_layout
          label: 主页布局设置
          addLabel: 添加布局
          min: 1
          max: 99
          itemType: object
          children:
            - $formkit: group
              index: "$index"
              name: layout_group
              id: layout_group
              label: 布局配置
              children:
                - $formkit: select
                  index: "$index"
                  name: layout_type
                  id: layout_type
                  label: 选择布局
                  value: "layout1"
                  options:
                    - label: 布局1
                      value: "layout1"
                    - label: 布局2
                      value: "layout2"
                    - label: 布局3
                      value: "layout3"
                - $formkit: group
                  index: "$index"
                  if: $get(layout_type).value == "layout1"
                  name: layout_groups
                  label: 布局1配置
                  children:
                    - $formkit: text
                      name: title
                      label: 1-1
                      value: "1-1"
                - $formkit: group
                  index: "$index"
                  if: $get(layout_type).value == "layout2"
                  name: layout_groups
                  label: 布局2配置
                  children:
                    - $formkit: text
                      name: title
                      label: 2-1
                      value: "2-1"
```
这个配置里，我想要在列表里根据if判断来配置不同的配置项。现在这样写，会导致在更改第二个group下的select时，将第一个的group也更改了

![image](https://github.com/halo-dev/halo/assets/32811349/3b143bc1-51ee-4d98-990a-958e45bface9)

需求是：我想配置多个布局模块(可重复)，然后渲染时循环配置做判断取值就好了。现在就是这个配置里的if有问题
请问有什么办法能解决我这个需求吗？

**Comment by chengzhongxue** [comment]
if: $value.widget == 'custom_html'

**Comment by chengzhongxue** [comment]
if: $value.layout_type == "layout1"

**Comment by ruibaby** [comment]
文档中有条件判断的示例：https://docs.halo.run/developer-guide/form-schema#%E7%A4%BA%E4%BE%8B-2

另外，用到 if 的地方建议加上 key 属性，尤其是 repeater 和 group。

**Comment by kecikeci** [comment]
> $value.layout_type

key属性加在哪里？能否给个示例，么么哒~

**Comment by ruibaby** [comment]
> > $value.layout_type
> 
> key属性加在哪里？能否给个示例，么么哒~

和 name、id 同级。

**Comment by kecikeci** [comment]
```
    - group: layout
      label: 布局设置
      formSchema:
        - $formkit: list
          name: index_layout
          label: 主页布局设置
          addLabel: 添加布局
          min: 1
          itemType: object
          children:
            - $formkit: group
              index: "$index"
              name: layout_group
              key: layout_group
              label: 布局模块配置
              children:
                - $formkit: select
                  name: layout_type
                  key: layout_type
                  label: 选择模块
                  value: "layout1"
                  options:
                    - label: 模块1
                      value: "layout1"
                    - label: 模块2
                      value: "layout2"
                    - label: 模块3
                      value: "layout3"
                - $formkit: group
                  if: $value.layout_type == "layout1"
                  name: layout_configs
                  key: layout_configs
                  label: 模块1配置
                  children:
                    - $formkit: repeater
                      name: banners
                      label: 轮播图
                      min: 1
                      value: []
                      children:
                        - $formkit: text
                          name: title
                          label: 标题
                        - $formkit: text
                          name: url
                          label: 链接
                        - $formkit: attachment
                          name: image
                          label: 图片
                - $formkit: group
                  if: $value.layout_type == "layout2"
                  name: layout_configs
                  key: layout_configs
                  label: 模块2配置
                  children:
                    - $formkit: text
                      name: title
                      label: 标题
                      value: ""
```

如图，在添加第二个块的时候，选到模块2时，if判断出来的样式会有问题，请问如何处理？

![image](https://github.com/user-attachments/assets/7f558294-6718-4e05-83dd-8ee92dc8083c)
