### ISSUE TITLE
插件或主题当条件渲染的设置项没有显示时会删除字段

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#7121]
### Prerequisites

- [x] I have searched for related issues in the [issues](https://github.com/halo-dev/halo/issues) list.
- [x] This is an issue with the Halo project itself. If it is not an issue with the project itself(For example: Installation and deployment issues.), it is recommended to submit it in the [Discussions](https://github.com/halo-dev/halo/discussions).
- [x] I have tried disabling all plugins to rule out plugins as the cause of the problem.
- [x] If it is an issue with plugins and themes, please submit it in the respective plugin and theme repositories.

### System information

No need system information

### What is the project operation method?

Docker

### What happened?

假如有以下表单定义
```yaml
  - $formkit: group
    label: 代理设置
    name: proxy
    children:
      - $formkit: checkbox
        label: 启用代理
        name: enabled
        id: enabled
        key: enabled
        value: false
      - $formkit: text
        if: "$get(enabled).value === true"
        label: 代理地址
        name: host
        validation: required
      - $formkit: text
        if: "$get(enabled).value === true"
        label: 代理端口
        name: port
        validation: required|Number|between:0,65535
```

渲染如下

![Image](https://github.com/user-attachments/assets/51d51753-ffca-4ce5-b2fd-380246cb7e53)

如果点击启用，然后填写相关字段，保存之后实例数据如下:
```json
{
    "proxy": {
          "enabled": true,
          "port": "123",
          "host": "abc"
     }
}
```
但当我取消勾选时保存结果如下
```json
{
    "proxy": {
          "enabled": false
     }
}
```
这样会导致下次启用时需要重新填写设置项，但是 2.20 之前并不是这样的行为，应该和 https://github.com/halo-dev/halo/pull/6661 有关

### Additional information

/kind bug
/area ui
/milestone 2.20.x
