### ISSUE TITLE
halo 2.20版本 使用docker-compose以及JAR模式安装，无法正确初始化，总是要求初始化系统

### ISSUE THREAD

**Issue by ghostLiulang** [halo-dev/halo#7294]
[halo.zip](https://github.com/user-attachments/files/19269923/halo.zip)

### 前置条件

- [x] 已经在 [issues](https://github.com/halo-dev/halo/issues) 列表中搜索了相关问题。
- [x] 这是 Halo 项目本身存在的问题，如果是非项目本身的问题（如：安装部署问题），建议在 [Discussions](https://github.com/halo-dev/halo/discussions) 提交。
- [x] 已经尝试过停用所有的插件，排除是插件导致的问题。
- [x] 如果是插件和主题的问题，请在对应的插件和主题仓库提交。

### 系统信息

外部访问地址：192.168.1.5
版本 2.20
数据库:mysql 5.7
操作系统: debian12 内核 6.12.17-amd64

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

http://192.168.1.2:3306
版本 2.20
MySQL版本: 5.7
配置文件信息

```yaml
#version: "3"

services:
  halo:
    image: registry.fit2cloud.com/halo/halo:2
    restart: on-failure:3
    network_mode: "host"
    volumes:
      - ./halo2:/root/.halo2
    environment:
      # JVM 参数，默认为 -Xmx256m -Xms256m，可以根据实际情况做调整，置空表示不添加 JVM 参数
      - JVM_OPTS=-Xmx1G
    command:
      # 修改为自己已有的 MySQL 配置
      - --spring.r2dbc.url=r2dbc:pool:mysql://localhost:3306/halo
      - --spring.r2dbc.username=root
      - --spring.r2dbc.password=123456
      - --spring.sql.init.platform=mysql
      # 外部访问地址，请根据实际需要修改
      - --halo.external-url=http://192.168.1.5:8090/
      # 端口号 默认8090
      - --server.port=8090
```

### 相关日志输出

```shell

```
