### ISSUE TITLE
连接远程数据库超级慢

### ISSUE THREAD

**Issue by mogody** [halo-dev/halo#910]
Server 版本：1.3.2
Admin 版本：1.2.0
数据库：MySQL 5.7.18
运行模式：production

如题，目前发现连接远程的数据库超级慢，我后端服务器在上海，然后数据库服务器在北京，都是用腾讯云的服务，数据库用的是云服务，而不是自建的；数据库方面排查延迟很低，ping都是在30ms左右，并且其他应用访问速度很快(其他应用服务器和halo博客在同一台机器(上海地域)，连接的是同一个mysql数据库(北京地域))

博客地址: https://www.mogody.com

可以随便打开一篇文章，速度是肉眼可见的慢，每个请求基本都是在3-4s左右。测试切换到内网数据库，访问速度有明显提升，每个请求差不多在300ms左右，但是还是不如 1.2.0 版本的

**Comment by JohnNiang** [comment]
如果切换为内网数据库变快了，应该想到之前的 3-4s 中的大部分延时是地域造成的。

**Comment by JohnNiang** [comment]
如果方便的话，建议开启 debug 模式，查看 halo 的详细日志，看每一步的耗时。

**Comment by mogody** [comment]
@JohnNiang 可如果是地域问题导致，那为何我其他应用，访问非常稳定；而且我切换为内网的话，速度明显不如1.2.0版本的，也是肉眼可见的差别

**Comment by mogody** [comment]
ok 那我排查下看看

**Comment by mogody** [comment]
@JohnNiang debug模式是哪个配置呢？

**Comment by JohnNiang** [comment]
> @JohnNiang debug模式是哪个配置呢？

在 `application.yml` 中新增配置以下内容：

```yml
logging:
  level:
    run.halo.app: DEBUG
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.hibernate.type.descriptor.sql.BasicExtractor: INFO
```
